<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Green space</title>
    </head>
    <body>
        <div class="caixa1">
            
			<div class="conteudo-titulo-index">
            <div class="img-logo">
                <img src="../img/logo.png" alt="logo">
            </div>
				<a href="/login" class="titulo-index">Conheça o projeto GreenSpace</a>
			</div>
		</div>

        <div class="conteudo-index">
			<h1 class="title-index">O que é o GreenSpace?</h1>
			<p class="text-index">O Green Space é um aplicativo inovador voltado para entusiastas de jardinagem, integrando funcionalidades de manejo de plantas e interação social em uma plataforma única. Ele permite aos usuários gerenciar suas plantações, acessar dicas de plantio, monitorar condições climáticas e interagir com uma comunidade de jardineiros. O Green Space oferece ferramentas para organizar o estoque de produtos de jardinagem e notificar sobre condições climáticas relevantes. Além disso, facilita a troca de informações e experiências entre os membros, promovendo um ambiente colaborativo e informativo.</p>

			
		</div>

        <div class="caixa2">
			
		</div>

        <div class="conteudo-index">
			<h1 class="title-index">Nossa ideia</h1>
			<p class="text-index">O Green Space também inclui funcionalidades para os usuários manterem registros detalhados de suas plantações, incluindo tipos de plantas, condições de cultivo, e preferências de cuidado. Através de um sistema de notificações, os usuários recebem alertas sobre mudanças climáticas que podem afetar suas plantações, garantindo uma gestão proativa. A plataforma permite a integração com fornecedores de produtos de jardinagem, facilitando a compra de insumos diretamente pelo aplicativo. Além disso, os usuários podem compartilhar suas experiências e conhecimentos no fórum da comunidade, ajudando outros jardineiros a resolver problemas e melhorar suas práticas de cultivo. O Green Space se destaca por sua interface intuitiva e por promover um ambiente de aprendizado contínuo e colaboração entre os amantes da jardinagem.</p>

		</div>
        
    </body>
</html>

