<html>
  <head>
    <meta charset="utf-8" />
    <title>Login - inicio</title>
    
  </head>

  <body class="fundo-login">
    <div class="container">    
      <div class="row">

        <div class="card-login">
          <div class="card">
            <div class="card-header">
              Login
            </div>
            <div class="card-body">
              <form action="/valida_login" method="post">
                <div class="form-group">
                  <label>Email</label>
                  <input name="email" type="email" class="form-control" id="form-email" placeholder="E-mail">
                  <?php

                  if(isset($_GET['login']) && $_GET['login'] == 'error1' ) { ?>
                  <script>
                      document.getElementById('form-email').className = 'form-control-error'
                  </script>

                  <?php } ?>           
                </div>


                <div class="form-group">
                  <label>Senha</label>
                  <input name="senha" type="password" class="form-control" id="form-senha" placeholder="Senha">
                  <?php

                  if(isset($_GET['login']) && $_GET['login'] == 'error1' ) { ?>

                  <script>
                      document.getElementById('form-senha').className = 'form-control-error'
                  </script>

                  <?php } ?>
                </div>

                <div class="create-account">
                  <p>Não possui uma conta? <a href="cadastro">Registrar-se</a></p>
                </div>

                <?php

                if(isset($_GET['login']) && $_GET['login'] == 'error1' ) { ?>
                  <div class="exception">
                      <p>Senha ou email incorreto!</p>
                  </div>

                <?php } ?>

                <?php

                if(isset($_GET['login']) && $_GET['login'] == 'error2' ) { ?>
                  <div class="exception">
                      <p>Faça login para iniciar!</p>
                  </div>

                <?php } ?>
           
                <button class="btn btn-lg btn-info btn-cadastro" type="submit">Entrar</button>
              </form>
            </div>
          </div>
        </div> 
    </div>
  </body>
</html>