<html>
  <head>
    <meta charset="utf-8" />
    <title>Login - redirecionar</title>
  </head>

  <body class="fundo-login">
    <div class="container">
      <div class="row">

        <div class="card-login">
          <div class="card">
            <div class="card-header">
              Parabens
            </div>
            <div class="card-body">
              <form action="cadastro_endereco" method="post">
                <div class="form-group">

                <div>
                  <p>Falta apenas 1 passo para você iniciar seu Jardim!!</p>
                </div>
           
                <button class="btn btn-lg btn-info btn-block btn-cadastro" type="submit">Cadastrar endereço</button>
              </form>
            </div>
          </div>
        </div> 
    </div>
  </body>
</html>