<html>
  <head>
    <meta charset="utf-8" />
    <title>Login - redirecionar</title>
  </head>

  <body>
    <div class="container">    
      <div class="row">

        <div class="card-login">
          <div class="card">
            <div class="card-header">
              Parabens
            </div>
            <div class="card-body">
              <form action="login" method="post">
                <div class="form-group">

                <div>
                  <p>Seu acesso foi cadastrado com sucesso!!</p>
                </div>
           
                <button class="btn btn-lg btn-info btn-block" type="submit">Ir para login</button>
              </form>
            </div>
          </div>
        </div> 
    </div>
  </body>
</html>