<html>
  <head>
    <meta charset="utf-8" />
    <title>Login - menu inicial</title>
  </head>

  <body>
    <div id="corpo-modulo-meu-jardim">

      <nav class="navbar navbar-expand-sm navbar-dark navbar-custom">
          <!--Logo-->
          <div class="navbar-brand">
            <span class="align-span"><?php echo $_SESSION["cidade"]  ?></span><span><?php echo $_SESSION["temperatura"]  ?>ºC</span> <img src="https://openweathermap.org/img/wn/<?php echo $_SESSION["icone"] ?>.png" alt='Weather Icon'> <span class="align-span"><?php echo $_SESSION["clima"] ?></span>
          </div>

          <!-- Menu Hamburguer -->
          <button class="navbar-toggler" data-toggle="collapse" data-target="#navegacao3">
            <span class="navbar-toggler-icon"></span>
          </button>

          <!--Navegaçao-->
        <div class="collapse navbar-collapse" id="navegacao3">
            <ul class="navbar-nav ml-auto">

                <li class="nav-item">
                  <a  class="nav-link msg-recepcao disabled">Olá 
                    
                  <?php
                        
                  if($_SESSION["Nome"]) {
                      
                  echo $_SESSION["Nome"] ?>                                                               
                  <?php } ?>

                  </a>
                </li>
                
                <li class="nav-item dropdown">
                  <a href="" class="nav-link msg-recepcao dropdown-toggle" data-toggle="dropdown">Meu Jardim</a>
                  <div class="dropdown-menu">
                    <a href="" class="dropdown-item">Serviço 1</a>
                    <a href="" class="dropdown-item">Serviço 2</a>
                    <a href="/sair" class="dropdown-item">Sair</a>
                  </div>



                </li>
            </ul>
        </div>
        
        </nav>
          <div class="container-custom">
            <div class="row">
              <div class="col-5 container-carousel">
                  <h1 class ="carousel-title">Minhas plantações</h1>
                    <div id="carousel-controles" class="carousel slide" data-ride="carousel"><!--Carousel -->
                      <div class="carousel-inner"><!--Inner -->
                        
                        <div class="carousel-item carousel-custom active">
                          <img src="../img/abobora.jpg" class="img-fluid">
                        </div>

                      </div><!--/Inner -->

                      <!-- Controles -->
                      <a href="#carousel-controles" class="carousel-control-prev" data-slide="prev">
                        <span class="carousel-control-prev-icon"></span>
                      </a>

                      <a href="#carousel-controles" class="carousel-control-next" data-slide="next">
                        <span class="carousel-control-next-icon"></span>
                      </a>

                    </div><!--/Carousel -->
                </div>
            </div>
          </div>
        </div>
  </body>
</html>