
<html>
  <head>
    <meta charset="utf-8" />
    <title>Login - Vendedores</title>

    <script>
        function comprar() {
            alert('Pedido solicitado, aguarde o retorno do vendedor!');
        }
    </script>

  </head>
  
  <body>
    <div id="corpo-modulo-meu-comercio">
      <nav class="navbar navbar-expand-sm navbar-dark navbar-custom">
          <!--Logo-->
          <div class="navbar-brand clima-custom">
            <?php echo $_SESSION["cidade"] ?><span class="align-span"></span><span><?php echo $_SESSION["temperatura"]  ?>ºC</span> <img src="https://openweathermap.org/img/wn/<?php echo $_SESSION["icone"] ?>.png" alt='Weather Icon'> <span class="align-span"><?php echo $_SESSION["clima"] ?></span>
          </div>

          <!-- Menu Hamburguer -->
          <button class="navbar-toggler" data-toggle="collapse" data-target="#navegacao3">
            <span class="navbar-toggler-icon"></span>
          </button>

          <!--Navegaçao-->
        <div class="collapse navbar-collapse" id="navegacao3">
            <ul class="navbar-nav ml-auto">

                <li class="nav-item">
                  <a  class="nav-link msg-recepcao disabled">Olá 
                    
                  <?php
                        
                  if($_SESSION["Nome"]) {
                      
                  echo $_SESSION["Nome"] ?>                                                               
                  <?php } ?>

                  </a>
                </li>
                
                <li class="nav-item dropdown">
                  <a href="" class="nav-link msg-recepcao dropdown-toggle" data-toggle="dropdown">Vendedores</a>
                  <div class="dropdown-menu">
                    <a href="/modulo_meu_jardim" class="dropdown-item">Meu Jardim</a>
                    <a href="/modulo_meu_comercio?user_stock" class="dropdown-item">Meu Comercio</a>
                    <a href="/modulo_comunidade" class="dropdown-item">Comunidade</a>                    
                    <a href="/sair" class="dropdown-item">Sair</a>
                  </div>

                </li>

            </ul>
        </div>
        
        </nav>
          <div class="container-custom">

          


          <?php if(empty($_GET)) { ?>    

          <div class="row justify-content-center">
            <div class="col-5"><h1 class ="carousel-title-branco">Vendedores</h1></div>
          </div>
          <div class="row justify-content-center">
            <div class="col-10 container-tipos-plantas">
              
            <div class="card-group container_flores">
            <?php
            $vendedores = $_SESSION['vendedores'];

            foreach ($vendedores as $vendedor) {
                echo "
                <div class='card-vendedores'>
                    <img class='img-card-vendedores' src='{$vendedor['Imagem']}' alt='Imagem do Produto'>
                    <h2 class='h2-card-vendedores'>{$vendedor['Produto_principal']}</h2>
                    <p><strong>Data Plantio:</strong> {$vendedor['DataPlantio']}</p>
                    <p><strong>Ramo Principal:</strong> {$vendedor['Ramo_principal']}</p>
                    <p><strong>Vendedor:</strong> {$vendedor['Nome']}</p>
                    <button class='btn-comprar' onclick='comprar()'>Comprar</button>
                </div>
                ";
            }
            ?>
            </div>

          <?php } ?>

          


          

          </div>
        </div>
  </body>

</html>